### ISSUE TITLE
Error running wgd

### ISSUE THREAD

**Issue by Bio1nform** [heche-psb/wgd#6]
Hi, 
This is great tool, i have used version 1. Now working with version2. I managed to install with conda, however i am getting following error

**wgd -h**
Usage: wgd [OPTIONS] COMMAND [ARGS]...
  wgd v2 - Copyright (C) 2023-2024 Hengchi Chen
  Contact: heche@psb.vib-ugent.be
Options:
  -v, --verbosity [info|debug]  Verbosity level, default = info.
  -h, --help                    Show this message and exit.
Commands:
  dmd    All-vs-all diamond blastp + MCL clustering.
  focus  Multiply species RBH or c-score defined orthologous family's gene...
  ksd    Paranome and one-to-one ortholog Ks distribution inference...
  mix    Mixture modeling of Ks distributions.
  peak   Infer peak and CI of Ks distribution.
  syn    Co-linearity and anchor inference using I-ADHoRe.
  viz    Visualization of Ks distribution or synteny

**wgd dmd**
09:04:59 INFO     This is wgd v1.2                                                                                                                             cli.py:32
Traceback (most recent call last):
  File "/home/.conda/envs/WGD/bin/wgd", line 10, in <module>
    sys.exit(cli())
  File "/home/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/.conda/envs/WGD/lib/python3.6/site-packages/cli.py", line 113, in dmd
    _dmd(**kwargs)
  File "/home/.conda/envs/WGD/lib/python3.6/site-packages/cli.py", line 116, in _dmd
    from wgd.core import SequenceData, read_MultiRBH_gene_families,mrbh,ortho_infer,genes2fams,endt,segmentsaps,bsog
ModuleNotFoundError: No module named 'wgd.core'

**wgd viz**
09:05:19 INFO     This is wgd v1.2                                                                                                                             cli.py:32
Traceback (most recent call last):
  File "/home/.conda/envs/WGD/bin/wgd", line 10, in <module>
    sys.exit(cli())
  File "/home/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/.conda/envs/WGD/lib/python3.6/site-packages/cli.py", line 533, in viz
    _viz(**kwargs)
  File "/home/.conda/envs/WGD/lib/python3.6/site-packages/cli.py", line 536, in _viz
    from wgd.viz import elmm_plot, apply_filters, multi_sp_plot, default_plot,all_dotplots,filter_by_minlength,dotplotunitgene,dotplotingene,filter_mingenumber
ImportError: cannot import name 'elmm_plot'

Any help would be great.
Thanks

**Comment by heche-psb** [comment]
Hi, thanks for the interest in `wgd v2`! Could you please try with python=3.6/3.7/3.8 and see if you would meet the same error? Besides, using `pip install wgd` is also an option.

**Comment by Bio1nform** [comment]
hi heche-psb, 

Thanks, I managed to install it in 3.8, and is working now.
I am confused with some steps, in the example:
 1) wgd dmd Aquilegia_coerulea (Is Aquilegia_coerulea folder or fasta? Including multiple fasta files did work for me)
 2) I am not able to get the families for the downstream analysis, which output from wgd dmd is families? 

Thank you.

**Comment by heche-psb** [comment]
Hi, The `Aquilegia_coerulea` is the file name of cds sequence. If you provide only 1 cds file, it will calculate the whole paranome. With more than 1 cds files, it will calculate global, local MRBH or just pairwise RBH according to the other options you set. The family output file of `wgd dmd Aquilegia_coerulea ` is `Aquilegia_coerulea.tsv` in the default output folder `wgd_dmd`, indicating the paralogous family. The workflow can be glanced at [here](https://wgdv2.readthedocs.io/en/latest/recipes.html).

**Comment by Bio1nform** [comment]
Hi, Thanks for the information. So i can use the MRBH as a family for the next steps.
I ran  wgd dmd Aquilegia_coerulea, and got Aquilegia_coerulea.tsv.

I a getting error with : 
wgd ksd wgd_dmd/Aquilegia_coerulea.tsv Aquilegia_coerulea	

[myjob.5830965_1.error.txt](https://github.com/heche-psb/wgd/files/12195864/myjob.5830965_1.error.txt)

**Comment by heche-psb** [comment]
I think it might be due to the version of `PAML`. Are you using `PAML` v4.9j? This version shall work fine.

**Comment by Bio1nform** [comment]
I am using PAML v4.9j still same error.

**Comment by heche-psb** [comment]
Could you please provide me with your input file? I will check if I may meet the same error.

**Comment by Bio1nform** [comment]
Here is the input fasta file.
[Aquilegia_coerulea.zip](https://github.com/heche-psb/wgd/files/12210832/Aquilegia_coerulea.zip)

**Comment by heche-psb** [comment]
I tried on your input file with command "wgd ksd wgd_dmd/Aquilegia_coerulea.txt.tsv Aquilegia_coerulea.txt" and it works. Maybe you could try it again? Thanks a lot.

**Comment by Bio1nform** [comment]
Hi, 

Thanks for taking time to look into it. It is working for now, there was issue with some software version. 
I am still trying to figure out some issues.

**a) wgd dmd** cds1.fasta cds2.fasta cds3.fasta --anchorpoints apdata --segments smdata --listelements ledata --genetable gtdata --collinearcoalescence

**b) wgd peak** wgd_ksd/Aquilegia_coerulea.tsv.ks.tsv --anchorpoints wgd_syn/iadhore-out/anchorpoints.txt --segments wgd_syn/iadhore-out/segments.txt --listelements wgd_syn/iadhore-out/list_elements.txt --multipliconpairs wgd_syn/iadhore-out/multiplicon_pairs.txt --weighted

I see some data requirement (--anchorpoints apdata --segments smdata --listelements ledata --genetable etc. In **b) wgd peak**, the source are pointed to wgd_syn). How are these data formed? How do i get these data?

Thanks

**Comment by Bio1nform** [comment]
Hi am getting error running this too. 

wgd ksd wgd_globalmrbh/global_MRBH.tsv --extraparanomeks wgd_ksd/Aquilegia_coerulea.tsv.ks.tsv -sp speciestree.nw --reweight -o wgd_globalmrbh_ks --spair "Aquilegia_coerulea;Protea_cynaroides" --spair "Aquilegia_coerulea;Vitis_vinifera" --spair "Aquilegia_coerulea;Acorus_americanus" --spair "Aquilegia_coerulea;Aquilegia_coerulea" --plotkde --nthreads 90 Aquilegia_coerulea Protea_cynaroides Acorus_americanus Vitis_vinifera

Help Please, Thanks

[myjob.6072966_1.error.txt](https://github.com/heche-psb/wgd/files/12244014/myjob.6072966_1.error.txt)

**Comment by Bio1nform** [comment]
Hi,
I am stuck in here, any help would be really appreciated.

Kindly help Please.
Thank you

**Comment by heche-psb** [comment]
Hi, please install the latest version here in the github repository. The error information shows that you're using an older version that might have bugs which I have already fixed later.

**Comment by Bio1nform** [comment]
Hi Thanks for the information. 

I installed wgd==2.0.20 version in python3.6.

wgd dmd --globalmrbh Aquilegia_coerulea Protea_cynaroides Acorus_americanus Vitis_vinifera -o wgd_globalmrbh

Now i get these errors:
  File "/home/.conda/envs/wgdV2/bin/wgd", line 10, in <module>
    sys.exit(cli())
  File "/home/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/.conda/envs/wgdV2/lib/python3.6/site-packages/cli.py", line 453, in ksd
    _ksd(**kwargs)
  File "/home/.conda/envs/wgdV2/lib/python3.6/site-packages/cli.py", line 457, in _ksd
    from wgd.core import get_gene_families, SequenceData, KsDistributionBuilder
ModuleNotFoundError: No module named 'wgd.core'

Thanks you

**Comment by Bio1nform** [comment]
With python3.8:

wgd dmd --globalmrbh Aquilegia_coerulea Protea_cynaroides Acorus_americanus Vitis_vinifera -o wgd_globalmrbh
**Works fine**

Rest does not work

wgd ksd wgd_globalmrbh_CHECK/global_MRBH.tsv --extraparanomeks wgd_ksd/Aquilegia_coerulea.tsv.ks.tsv -sp speciestree.nw --reweight -o wgd_globalmrbh_ks1 --spair "Aquilegia_coerulea;Protea_cynaroides" --spair "Aquilegia_coerulea;Vitis_vinifera" --spair "Aquilegia_coerulea;Acorus_americanus" --spair "Aquilegia_coerulea;Aquilegia_coerulea" --plotkde Aquilegia_coerulea Protea_cynaroides Acorus_americanus Vitis_vinifera

Thank you.

[myjob.error.txt](https://github.com/heche-psb/wgd/files/12317244/myjob.error.txt)

**Comment by heche-psb** [comment]
The error occurred at the this step `kde = stats.gaussian_kde(y,weights=w,bw_method=0.1)`, which returned `ValueError: array must not contain infs or NaNs.` The problem is between the Ks file, species pairs and the species tree. I guess it might be due to some incorrect inputs. Could you please share me with all your input and the used full command. Thanks!

**Comment by Bio1nform** [comment]
Hi, 
I ran the following steps.
Here are the sequence files:
[Sequences1.tar.gz](https://github.com/heche-psb/wgd/files/12337094/Sequences1.tar.gz)
[Sequences2.tar.gz](https://github.com/heche-psb/wgd/files/12337106/Sequences2.tar.gz)

1) wgd ksd

 wgd_dmd/Aquilegia_coerulea.tsv Aquilegia_coerulea
[wgd_ksd.zip](https://github.com/heche-psb/wgd/files/12336403/wgd_ksd.zip)

2) wgd dmd --g lobalmrbh Aquilegia_coerulea Protea_cynaroides Acorus_americanus Vitis_vinifera -o wgd_globalmrbh

[wgd_globalmrbh.zip](https://github.com/heche-psb/wgd/files/12335771/wgd_globalmrbh.zip)

3) wgd ksd wgd_globalmrbh/global_MRBH.tsv --extraparanomeks wgd_ksd/Aquilegia_coerulea.tsv.ks.tsv -sp speciestree.nw --reweight -o wgd_globalmrbh_ks1 --spair "Aquilegia_coerulea;Protea_cynaroides" --spair "Aquilegia_coerulea;Vitis_vinifera" --spair "Aquilegia_coerulea;Acorus_americanus" --spair "Aquilegia_coerulea;Aquilegia_coerulea" --plotkde Aquilegia_coerulea Protea_cynaroides Acorus_americanus Vitis_vinifera 

I get the error message.

Thanks

**Comment by Bio1nform** [comment]
Hi,

Were you able to take a look into it?

Thanks,

**Comment by heche-psb** [comment]
Hi, yes, there was a small bug concerning the node-averaged Ks processing. I just fixed it and pushed it as a `v2.0.21`. Please try again and let me know if the same error occurred again. Thanks a lot!

**Comment by Bio1nform** [comment]
Hi, I am still getting error.
[job.error.txt](https://github.com/heche-psb/wgd/files/12414167/job.error.txt)

**Comment by heche-psb** [comment]
Hi, I think you're using `wgd ksd` to do the rate correction. Could you use `wgd ksd` to only infer Ks while using `wgd viz` to do the rate correction?

**Comment by Bio1nform** [comment]
Thanks it seems to work, i will let you know if there is any issue in this.

However, wgd dmd --globalmrbh i think it cannot handle sequence larger than 4kb. Is there any way i can increase the size? I am not sure what is the reason though.

**I get the following error.**

[error1.txt](https://github.com/heche-psb/wgd/files/12424849/error1.txt)

**Comment by heche-psb** [comment]
Could you please share me with the sequence files that you used? It seems to be a format problem of the input cds files.

**Comment by Bio1nform** [comment]
I figured the error. It was because of duplicated fasta IDs. Is there any way to fix this issue?

How ever, some new error.
wgd ksd wgd_dmd/Aquilegia_coerulea.tsv Aquilegia_coerulea -o wgd_ksd
gives me following error.
[error2.txt](https://github.com/heche-psb/wgd/files/12433792/error2.txt)

**Comment by heche-psb** [comment]
The problem occurred at the family `GF00000004`. Could you please share me with the cds files of only `GF00000004`.

**Comment by Bio1nform** [comment]
Here you go.
GF00000004	AQUCO_02000225v1_22779, AQUCO_00700295v1_9186, AQUCO_02000226v1_22780, AQUCO_44500001v1_40958, AQUCO_02000219v1_22773, AQUCO_00201007v1_3153, AQUCO_02200206v1_24148, AQUCO_04400082v1_33100, AQUCO_01000140v1_12868, AQUCO_01000578v1_13622, AQUCO_00700296v1_9187, AQUCO_00200174v1_1785, AQUCO_00700480v1_9470, AQUCO_01000288v1_13135, AQUCO_00200153v1_1743, AQUCO_00900240v1_11191, AQUCO_00200176v1_1787, AQUCO_01500005v1_18737, AQUCO_04700045v1_33731, AQUCO_01700324v1_20762, AQUCO_00700388v1_9339, AQUCO_01700327v1_20765, AQUCO_00700386v1_9337, AQUCO_02600114v1_25914, AQUCO_00500170v1_7139, AQUCO_00900126v1_11012, AQUCO_00200172v1_1783, AQUCO_03500197v1_30294, AQUCO_03900098v1_31723, AQUCO_02200275v1_24279, AQUCO_00300143v1_4243, AQUCO_03000303v1_28394, AQUCO_00200152v1_1742, AQUCO_00200155v1_1745, AQUCO_00400487v1_6293, AQUCO_29600001v1_40929, AQUCO_00300388v1_4628, AQUCO_00300391v1_4632, AQUCO_29600002v1_40930, AQUCO_04700046v1_33732, AQUCO_00200173v1_1784, AQUCO_00300142v1_4242, AQUCO_00200311v1_2025, AQUCO_11400002v1_40231, AQUCO_00200175v1_1786, AQUCO_04900044v1_33977, AQUCO_02300181v1_24692, AQUCO_00500129v1_7067, AQUCO_02300178v1_24689, AQUCO_01600057v1_19597, AQUCO_02300171v1_24678, AQUCO_02300176v1_24687, AQUCO_02300176v1_24686, AQUCO_02600115v1_25915, AQUCO_02300180v1_24691, AQUCO_00500071v1_6981, AQUCO_02800270v1_27588, AQUCO_00300386v1_4626, AQUCO_01600365v1_20054, AQUCO_00300389v1_4629, AQUCO_02500191v1_25430, AQUCO_00500071v1_6982, AQUCO_02900102v1_27824, AQUCO_02400108v1_24976, AQUCO_00100892v1_1485, AQUCO_01700027v1_20240, AQUCO_03700288v1_31162, AQUCO_07500004v1_37851, AQUCO_00500071v1_6983, AQUCO_00100478v1_811, AQUCO_00700290v1_9176, AQUCO_00300387v1_4627, AQUCO_07500004v1_37852, AQUCO_03700288v1_31161, AQUCO_00700293v1_9182, AQUCO_02300179v1_24690, AQUCO_00500071v1_6984, AQUCO_02300173v1_24683

[GF00000004.txt](https://github.com/heche-psb/wgd/files/12440190/GF00000004.txt)

**Comment by heche-psb** [comment]
I can actually run this family through successfully with command `wgd ksd famback.tsv GF00000004.cds`. Were you using `PAML v4.9j` and did you add other parameters?

![famback tsv ksd](https://github.com/heche-psb/wgd/assets/75600428/6bc42830-68e9-4c7a-ba7c-1c721cb88d47)

**Comment by Bio1nform** [comment]
I am using paml 4.9. i tried **wgd ksd GF0000000.tsv GF00000004 -o TEST** i get the following error. 

(WGDV2_38) geno@farm:\~/WGD/Aquilegia$ which codeml
**/home/software/GENOMETOOLS/PAML/paml4.9j/bin/codeml**
(WGDV2_38) geno@farm:~/WGD/Aquilegia$ wgd ksd GF0000000.tsv GF00000004 -o TEST
09:40:34 INFO     This is wgd v2.0.21                                                                                cli.py:32
09:40:36 INFO     tmpdir = wgdtmp_f2922255-bc2a-445e-826b-0fe0ce138647                                              cli.py:483
Traceback (most recent call last):
  File "/home/.conda/envs/WGDV2_38/bin/wgd", line 10, in <module>
    sys.exit(cli())
  File "/home/.conda/envs/WGDV2_38/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/.conda/envs/WGDV2_38/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/.conda/envs/WGDV2_38/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/.conda/envs/WGDV2_38/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/.conda/envs/WGDV2_38/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/.conda/envs/WGDV2_38/lib/python3.8/site-packages/cli.py", line 464, in ksd
    _ksd(**kwargs)
  File "/home/.conda/envs/WGDV2_38/lib/python3.8/site-packages/cli.py", line 490, in _ksd
    ksdb.get_distribution()
  File "/home/.conda/envs/WGDV2_38/lib/python3.8/site-packages/wgd/core.py", line 3030, in get_distribution
    df = pd.concat([pd.read_csv(x.out, index_col=0)
  File "/home/.conda/envs/WGDV2_38/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/.conda/envs/WGDV2_38/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 347, in concat
    op = _Concatenator(
  File "/home/.conda/envs/WGDV2_38/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 404, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate

**Comment by heche-psb** [comment]
I used another dataset and reproduced this error. It's because of the error in codeml "166 columns are converted into ??? because of stop codons. 21 out of 21 sequences do not have any resolved nucleotides. Giving up." It's the sequence that is not a strict cds and contains many in-frame stop codons so despite the stripped alignment length is not zero, no codeml result is returned. I just pushed a fixed commit so it should be solved now.

**Comment by Bio1nform** [comment]
Did you push it to new version?
I re-installed wgd2==2.0.21. I am still getting same error.

(wgdV2_38) geno@farm:~/WGD/Aquilegia$ **wgd ksd test.tsv GF00000004 -o TEST** gives me the same error. 

adding --cds gives me following error:

(wgdV2_38) geno@farm:~/WGD/Aquilegia$ **wgd ksd --cds test.tsv GF00000004 -o TEST**
07:50:05 INFO     This is wgd v2.0.21                                                                         cli.py:32
07:50:06 WARNING  Translation error (First codon 'AAG' is not a start codon) in seq AQUCO_00100478v1_811    core.py:282
         WARNING  Translation error (First codon 'TTA' is not a start codon) in seq AQUCO_00200173v1_1784   core.py:282
         WARNING  Translation error (First codon 'TTA' is not a start codon) in seq AQUCO_00200175v1_1786   core.py:282
         WARNING  Translation error (Final codon 'GTT' is not a stop codon) in seq AQUCO_00300391v1_4632    core.py:282
         WARNING  Translation error (First codon 'GCC' is not a start codon) in seq AQUCO_04900044v1_33977  core.py:282
         WARNING  Translation error (Final codon 'ACT' is not a stop codon) in seq AQUCO_29600002v1_40930   core.py:282
         INFO     tmpdir = wgdtmp_aaa2e529-da43-4116-b682-7bb00d94135e                                       cli.py:483
Traceback (most recent call last):
  File "/home/.conda/envs/wgdV2_38/bin/wgd", line 10, in <module>
    sys.exit(cli())
  File "/home/.conda/envs/wgdV2_38/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/.conda/envs/wgdV2_38/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/.conda/envs/wgdV2_38/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/.conda/envs/wgdV2_38/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/.conda/envs/wgdV2_38/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/.conda/envs/wgdV2_38/lib/python3.8/site-packages/cli.py", line 464, in ksd
    _ksd(**kwargs)
  File "/home/.conda/envs/wgdV2_38/lib/python3.8/site-packages/cli.py", line 490, in _ksd
    ksdb.get_distribution()
  File "/home/.conda/envs/wgdV2_38/lib/python3.8/site-packages/wgd/core.py", line 3030, in get_distribution
    df = pd.concat([pd.read_csv(x.out, index_col=0)
  File "/home/.conda/envs/wgdV2_38/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrappe             r
    return func(*args, **kwargs)
  File "/home/.conda/envs/wgdV2_38/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 347, in con             cat
    op = _Concatenator(
  File "/home/.conda/envs/wgdV2_38/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 404, in __i             nit__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate

**Comment by heche-psb** [comment]
Hi, you need to download and install the version from this github repository. I fixed some bugs later after the PYPI version `v2.0.21`. Sorry for the confusion.

**Comment by Bio1nform** [comment]
Hi, 

Others are working now. I am still getting error when i add **--plotapgmm.** 

**wgd viz -d wgd_globalmrbh_ks/global_MRBH.tsv.ks.tsv --extraparanomeks wgd_ksd/Aquilegia_coerulea.tsv.ks.tsv -sp speciestree.nw --reweight -ap wgd_syn/iadhore-out/anchorpoints.txt -o wgd_viz_mixed_Ks_elmm2 --spair "Aquilegia_coerulea;Protea_cynaroides" --spair "Aquilegia_coerulea;Vitis_vinifera" --spair "Aquilegia_coerulea;Acorus_americanus" --spair "Aquilegia_coerulea;Aquilegia_coerulea" --gsmap wgd_globalmrbh_ks/gene_species.map --plotkde --plotelmm --plotapgmm**

Traceback (most recent call last):
  File "/home/.conda/envs/wgdV2_38/bin/wgd", line 10, in <module>
    sys.exit(cli())
  File "/home/.conda/envs/wgdV2_38/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/.conda/envs/wgdV2_38/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/.conda/envs/wgdV2_38/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/.conda/envs/wgdV2_38/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/.conda/envs/wgdV2_38/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/.conda/envs/wgdV2_38/lib/python3.8/site-packages/cli.py", line 554, in viz
    _viz(**kwargs)
  File "/home/.conda/envs/wgdV2_38/lib/python3.8/site-packages/cli.py", line 594, in _viz
    multi_sp_plot(df,spair,gsmap,outdir,onlyrootout,title=prefix,ylabel=ylabel,viz=True,plotkde=plotkde,reweight=False,sptree=speciestree,ap = anchorpoints, extraparanomeks=extraparanomeks,plotapgmm=plotapgmm,plotelmm=plotelmm,components=components,max_EM_iterations=em_iterations,num_EM_initializations=em_initializations,peak_threshold=prominence_cutoff,rel_height=rel_height, na=True,user_xlim=xlim,user_ylim=ylim)
  File "/home/.conda/envs/wgdV2_38/lib/python3.8/site-packages/wgd/viz.py", line 665, in multi_sp_plot
    if plotapgmm: ax = addapgmm(ax,y,w,components,outdir,Hs)
  File "/home/.conda/envs/wgdV2_38/lib/python3.8/site-packages/wgd/viz.py", line 338, in addapgmm
    models, aic, bic, besta, bestb, N = fit_gmm(aic_bic_fplot, X_log, 2352890, components[0], components[1], em_iter=200, n_init=200)
  File "/home/.conda/envs/wgdV2_38/lib/python3.8/site-packages/wgd/viz.py", line 233, in fit_gmm
    models[i-n1] = mixture.GaussianMixture(n_components = i, covariance_type='full', max_iter = em_iter, n_init = n_init, random_state = seed).fit(X)
  File "/home/.conda/envs/wgdV2_38/lib/python3.8/site-packages/sklearn/mixture/_base.py", line 193, in fit
    self.fit_predict(X, y)
  File "/home/.conda/envs/wgdV2_38/lib/python3.8/site-packages/sklearn/mixture/_base.py", line 220, in fit_predict
    X = _check_X(X, self.n_components, ensure_min_samples=2)
  File "/home/.conda/envs/wgdV2_38/lib/python3.8/site-packages/sklearn/mixture/_base.py", line 52, in _check_X
    X = check_array(X, dtype=[np.float64, np.float32],
  File "/home/.conda/envs/wgdV2_38/lib/python3.8/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
  File "/home/.conda/envs/wgdV2_38/lib/python3.8/site-packages/sklearn/utils/validation.py", line 651, in check_array
    raise ValueError("Found array with %d sample(s) (shape=%s) while a"
ValueError: Found array with 0 sample(s) (shape=(0, 1)) while a minimum of 2 is required.

Thanks

**Comment by heche-psb** [comment]
Hi, could you first check if the gene ids in `wgd_ksd/Aquilegia_coerulea.tsv.ks.tsv` match exactly with the gene ids in `wgd_syn/iadhore-out/anchorpoints.txt`. It seems the `anchor Ks` data is not properly extracted as expected.

**Comment by Bio1nform** [comment]
Hi, I am getting this error with the .22 version.

**wgd syn -f mRNA -a Name wgd_dmd/Aquilegia_coerulea.tsv Aquilegia_coerulea.gff3 -ks wgd_ksd/Aquilegia_coerulea.tsv.ks.tsv -o wgd_sync**

  File "/home/.conda/envs/wgdV2_38/bin/wgd", line 10, in <module>
    sys.exit(cli())
  File "/home/.conda/envs/wgdV2_38/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/.conda/envs/wgdV2_38/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/.conda/envs/wgdV2_38/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/.conda/envs/wgdV2_38/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/.conda/envs/wgdV2_38/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/.conda/envs/wgdV2_38/lib/python3.8/site-packages/cli.py", line 641, in syn
    _syn(**kwargs)
  File "/home/.conda/envs/wgdV2_38/lib/python3.8/site-packages/cli.py", line 699, in _syn
    ksdb_df = formatv2(ksdb_df)
  File "/home/.conda/envs/wgdV2_38/lib/python3.8/site-packages/wgd/utils.py", line 27, in formatv2
    if "weightoutlierexcluded" not in ksdf.columns: weight_inc = get_outlierincluded(ksdf)
  File "/home/.conda/envs/wgdV2_38/lib/python3.8/site-packages/wgd/utils.py", line 48, in get_outlierincluded
    weight_inc = 1/df.groupby(['family', 'node'])['dS'].transform('count')
  File "/home/.conda/envs/wgdV2_38/lib/python3.8/site-packages/pandas/core/frame.py", line 7721, in groupby
    return DataFrameGroupBy(
  File "/home/.conda/envs/wgdV2_38/lib/python3.8/site-packages/pandas/core/groupby/groupby.py", line 882, in __init__
    grouper, exclusions, obj = get_grouper(
  File "/home/.conda/envs/wgdV2_38/lib/python3.8/site-packages/pandas/core/groupby/grouper.py", line 882, in get_grouper
    raise KeyError(gpr)
KeyError: 'node'

Thanks

**Comment by heche-psb** [comment]
Could you show me the column name of the file `wgd_ksd/Aquilegia_coerulea.tsv.ks.tsv`? Was it produced from v1 or v2?

**Comment by Bio1nform** [comment]
pair	family	g1	g2	gene1	gene2
Aqcoe1G119100.1__Aqcoe3G278800.1	GF00000001	Aquilegia_coerulea_40904	Aquilegia_coerulea_26689	Aqcoe3G278800.1	Aqcoe1G119100.1
Aqcoe2G086700.1__Aqcoe3G278800.1	GF00000001	Aquilegia_coerulea_40904	Aquilegia_coerulea_04209	Aqcoe3G278800.1	Aqcoe2G086700.1

This was produced from wgd2==2.0.22

**Comment by heche-psb** [comment]
It seems that there is no Ks results in your `wgd_ksd/Aquilegia_coerulea.tsv.ks.tsv`. Your run of last step using `wgd ksd` is problematic. May I have a look of the log file of the `wgd ksd` step that produced this file `wgd_ksd/Aquilegia_coerulea.tsv.ks.tsv`?

**Comment by Bio1nform** [comment]
**The  wgd2==2.0.21 works, Its the wgd2==2.0.22 that shows error.**

Wgd2==2.0.21 error.
[myjob. wgd2==2.0.21.txt](https://github.com/heche-psb/wgd/files/12581554/myjob.wgd2.2.0.21.txt)

Wgd2==2.0.22 error.
[myjoberror wgd2==2.0.22.txt](https://github.com/heche-psb/wgd/files/12581550/myjoberror.wgd2.2.0.22.txt)

**Comment by heche-psb** [comment]
Hi, it's a bug in `2.0.22`. I fixed it already in this repository. The fixed version is on `2.0.23` now. Sorry for the confusion.

**Comment by Bio1nform** [comment]
Thanks, I will try it. Is it updated on conda version too??

**Comment by heche-psb** [comment]
The update on conda will be a bit late. It's on PYPI now.

**Comment by Bio1nform** [comment]
I get issues installing (PYPI) in cluster. Installing Numpy, fastcluster give me issues.

 pip install numpy==1.19.0
Collecting numpy==1.19.0
  Using cached numpy-1.19.0.zip (7.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [58 lines of output]
      Running from numpy source directory.
      <string>:460: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      /scratch/tmp/pip-install-h122amxc/numpy_01c3c1595190499da8881a392ed6b0de/tools/cythonize.py:73: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        required_version = LooseVersion('0.29.14')
      /scratch/tmp/pip-install-h122amxc/numpy_01c3c1595190499da8881a392ed6b0de/tools/cythonize.py:75: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        if LooseVersion(cython_version) < required_version:
      warning: /scratch/tmp/pip-install-h122amxc/numpy_01c3c1595190499da8881a392ed6b0de/numpy/__init__.pxd:17:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: _philox.pyx:19:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: /scratch/tmp/pip-install-h122amxc/numpy_01c3c1595190499da8881a392ed6b0de/numpy/__init__.pxd:17:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  self.rng_state.ctr.v[i] = counter[i]

              self._reset_state_variables()

              self._bitgen.state = <void *>&self.rng_state
              self._bitgen.next_uint64 = &philox_uint64
                                         ^
      ------------------------------------------------------------

      _philox.pyx:195:35: Cannot assign type 'uint64_t (*)(void *) except? -1 nogil' to 'uint64_t (*)(void *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to type 'uint64_t (void *) except? -1 nogil'.
      Processing numpy/random/_bounded_integers.pxd.in
      Processing numpy/random/mtrand.pyx
      Processing numpy/random/_philox.pyx
      Traceback (most recent call last):
        File "/scratch/tmp/pip-install-h122amxc/numpy_01c3c1595190499da8881a392ed6b0de/tools/cythonize.py", line 235, in <module>
          main()
        File "/scratch/tmp/pip-install-h122amxc/numpy_01c3c1595190499da8881a392ed6b0de/tools/cythonize.py", line 231, in main
          find_process_files(root_dir)
        File "/scratch/tmp/pip-install-h122amxc/numpy_01c3c1595190499da8881a392ed6b0de/tools/cythonize.py", line 222, in find_process_files
          process(root_dir, fromfile, tofile, function, hash_db)
        File "/scratch/tmp/pip-install-h122amxc/numpy_01c3c1595190499da8881a392ed6b0de/tools/cythonize.py", line 188, in process
          processor_function(fromfile, tofile)
        File "/scratch/tmp/pip-install-h122amxc/numpy_01c3c1595190499da8881a392ed6b0de/tools/cythonize.py", line 77, in process_pyx
          subprocess.check_call(
        File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/home/software/wgd/ENV/bin/python', '-m', 'cython', '-3', '--fast-fail', '-o', '_philox.c', '_philox.pyx']' returned non-zero exit status 1.
      Cythonizing sources
      Traceback (most recent call last):
        File "/home/software/wgd/ENV/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/software/wgd/ENV/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/software/wgd/ENV/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/scratch/tmp/pip-build-env-jn2635rn/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 396, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/scratch/tmp/pip-build-env-jn2635rn/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/scratch/tmp/pip-build-env-jn2635rn/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 489, in <module>
        File "<string>", line 469, in setup_package
        File "<string>", line 274, in generate_cython
      RuntimeError: Running cythonize failed!
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Installed cython, still similar issue.
Conda only works for me.

**Comment by heche-psb** [comment]
Hi, please try with `python3.8`. `python3.10` is not compatible for now.

**Comment by Bio1nform** [comment]
This error:

python setup.py install                                             Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from setuptools import setup
  File "/home/wgd/ENV/lib/python3.8/site-packages/setuptools/__init__.py", line 19, in <module>
    from setuptools.dist import Distribution
  File "/home/wgd/ENV/lib/python3.8/site-packages/setuptools/dist.py", line 34, in <module>
    from setuptools import windows_support
  File "/home/wgd/ENV/lib/python3.8/site-packages/setuptools/windows_support.py", line 2, in <module>
    import ctypes
  File "/home/software/Python/Python-3.8.5/Lib/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.6: cannot open shared object file: No such file or directory

**Comment by heche-psb** [comment]
Hi, you may try with `sudo apt-get install libffi-dev` or update.

**Comment by Bio1nform** [comment]
I am working in cluster and do not have the admin privilege.
The previous error was with: **python setup.py install**

With : **python -m pip install -r requirements.txt** 
I get following error.

WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/attrs/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/attrs/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/attrs/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/attrs/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/attrs/
Could not fetch URL https://pypi.org/simple/attrs/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/attrs/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement attrs==20.3.0 (from -r requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for attrs==20.3.0 (from -r requirements.txt (line 1))
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping

**Comment by heche-psb** [comment]
Above you were installing from the cloned repository right? Normally `python3.8` works. Did you install with virtual environment?

**Comment by Bio1nform** [comment]
This error is from the virtual environment.

**Comment by heche-psb** [comment]
The error messages indicate there are issues with the installed python which should have SSL support but apparently not. This is not a problem of wgd v2 itself I guess.

**Comment by Bio1nform** [comment]
No, not the issue with wgd V2. I am trying to install the V==2.1.23 as of now. 
Once i install i will check for the bug that you have updated.
How long will the conda update take? conda version works best for me.

**Comment by Bio1nform** [comment]
I installed the V==2.0.23. in PYPI.

**wgd ksd wgd_dmd/Aquilegia_coerulea.tsv Aquilegia_coerulea -o wgd_ksd**

15:20:53 INFO     This is wgd v2.0.23                                  cli.py:32
15:21:10 INFO     tmpdir =                                            cli.py:483
                  wgdtmp_adab2f7f-fb6b-407e-8083-5643b9b4a9fc                   
15:21:14 INFO     Analysing family GF00000001                       core.py:2873
15:21:14 INFO     Analysing family GF00000002                       core.py:2873
15:21:14 INFO     Analysing family GF00000003                       core.py:2873
15:21:14 INFO     Analysing family GF00000004                       core.py:2873
15:21:15 INFO     Analysing family GF00000005                       core.py:2873

Now i get the following error.
[error.txt](https://github.com/heche-psb/wgd/files/12591382/error.txt)

**Comment by Bio1nform** [comment]
I installed the V==2.0.23. in Conda.

**wgd ksd wgd_dmd/Aquilegia_coerulea.tsv Aquilegia_coerulea -o wgd_ksd**

Still some error.

19:28:57 INFO     This is wgd v2.0.23                                  cli.py:32
19:29:08 INFO     tmpdir =                                            cli.py:483
                  wgdtmp_d51006c1-8f52-4211-9f39-423941314e0c                   
19:29:13 INFO     Analysing family GF00000001                       core.py:2873
19:29:13 INFO     Analysing family GF00000002                       core.py:2873
19:29:13 INFO     Analysing family GF00000003                       core.py:2873
19:29:13 INFO     Analysing family GF00000004                       core.py:2873
19:29:27 WARNING  Stripped alignment length == 0 for GF00000004    codeml.py:225
         INFO     Analysing family GF00000005                       core.py:2873
19:29:36 WARNING  Stripped alignment length == 0 for GF00000002    codeml.py:225
         INFO     Analysing family GF00000006                       core.py:2873
19:29:39 WARNING  No codeml result for GF00000003 due to no        codeml.py:234
                  resolved nucleotides                                          

                                        
19:55:59 WARNING  No codeml result for GF00006547 due to no        codeml.py:234
                  resolved nucleotides                                          
19:56:16 INFO     Saving to wgd_ksd/Aquilegia_coerulea.tsv.ks.tsv    cli.py:493
19:56:18 INFO     Making plots                                        cli.py:495
         INFO     No valid Ks values for plotting                     cli.py:497

**Comment by heche-psb** [comment]
> I installed the V==2.0.23. in PYPI.
> 
> **wgd ksd wgd_dmd/Aquilegia_coerulea.tsv Aquilegia_coerulea -o wgd_ksd**
> 
> 15:20:53 INFO This is wgd v2.0.23 cli.py:32 15:21:10 INFO tmpdir = cli.py:483 wgdtmp_adab2f7f-fb6b-407e-8083-5643b9b4a9fc 15:21:14 INFO Analysing family GF00000001 core.py:2873 15:21:14 INFO Analysing family GF00000002 core.py:2873 15:21:14 INFO Analysing family GF00000003 core.py:2873 15:21:14 INFO Analysing family GF00000004 core.py:2873 15:21:15 INFO Analysing family GF00000005 core.py:2873
> 
> Now i get the following error. [error.txt](https://github.com/heche-psb/wgd/files/12591382/error.txt)

This error shows something wrong with the alignment of GF00000001. Could you find the tmp dir for this family and share me with the `GF00000001.cdsaln` `GF00000001.codeml` `GF00000001.ctrl` `pro.aln` files.

**Comment by heche-psb** [comment]
> I installed the V==2.0.23. in Conda.
> 
> **wgd ksd wgd_dmd/Aquilegia_coerulea.tsv Aquilegia_coerulea -o wgd_ksd**
> 
> Still some error.
> 
> 19:28:57 INFO This is wgd v2.0.23 cli.py:32 19:29:08 INFO tmpdir = cli.py:483 wgdtmp_d51006c1-8f52-4211-9f39-423941314e0c 19:29:13 INFO Analysing family GF00000001 core.py:2873 19:29:13 INFO Analysing family GF00000002 core.py:2873 19:29:13 INFO Analysing family GF00000003 core.py:2873 19:29:13 INFO Analysing family GF00000004 core.py:2873 19:29:27 WARNING Stripped alignment length == 0 for GF00000004 codeml.py:225 INFO Analysing family GF00000005 core.py:2873 19:29:36 WARNING Stripped alignment length == 0 for GF00000002 codeml.py:225 INFO Analysing family GF00000006 core.py:2873 19:29:39 WARNING No codeml result for GF00000003 due to no codeml.py:234 resolved nucleotides
> 
> 19:55:59 WARNING No codeml result for GF00006547 due to no codeml.py:234 resolved nucleotides 19:56:16 INFO Saving to wgd_ksd/Aquilegia_coerulea.tsv.ks.tsv cli.py:493 19:56:18 INFO Making plots cli.py:495 INFO No valid Ks values for plotting cli.py:497

Conda wouldn't install `paml v4.9j` automately, some other versions instead. Could you double check the `paml` version in your conda environment for `wgd`?

**Comment by Bio1nform** [comment]
> > I installed the V==2.0.23. in PYPI.
> > **wgd ksd wgd_dmd/Aquilegia_coerulea.tsv Aquilegia_coerulea -o wgd_ksd**
> > 15:20:53 INFO This is wgd v2.0.23 cli.py:32 15:21:10 INFO tmpdir = cli.py:483 wgdtmp_adab2f7f-fb6b-407e-8083-5643b9b4a9fc 15:21:14 INFO Analysing family GF00000001 core.py:2873 15:21:14 INFO Analysing family GF00000002 core.py:2873 15:21:14 INFO Analysing family GF00000003 core.py:2873 15:21:14 INFO Analysing family GF00000004 core.py:2873 15:21:15 INFO Analysing family GF00000005 core.py:2873
> > Now i get the following error. [error.txt](https://github.com/heche-psb/wgd/files/12591382/error.txt)
> 
> This error shows something wrong with the alignment of GF00000001. Could you find the tmp dir for this family and share me with the `GF00000001.cdsaln` `GF00000001.codeml` `GF00000001.ctrl` `pro.aln` files.

These are the only files that are present in GF00000001.

[pro.aln.txt](https://github.com/heche-psb/wgd/files/12598076/pro.aln.txt)
[pro.fasta.txt](https://github.com/heche-psb/wgd/files/12598077/pro.fasta.txt)

**Comment by heche-psb** [comment]
Manually run `MAFFT` is no problem on your `pro.fasta.txt`. It seems something went wrong during the `MAFFT` analysis. Is `MAFFT` working properly in your environment on huge family like `GF00000001`? One suspect is that you didn't give enough cpu to the job.

**Comment by Bio1nform** [comment]
> > I installed the V==2.0.23. in Conda.
> > **wgd ksd wgd_dmd/Aquilegia_coerulea.tsv Aquilegia_coerulea -o wgd_ksd**
> > Still some error.
> > 19:28:57 INFO This is wgd v2.0.23 cli.py:32 19:29:08 INFO tmpdir = cli.py:483 wgdtmp_d51006c1-8f52-4211-9f39-423941314e0c 19:29:13 INFO Analysing family GF00000001 core.py:2873 19:29:13 INFO Analysing family GF00000002 core.py:2873 19:29:13 INFO Analysing family GF00000003 core.py:2873 19:29:13 INFO Analysing family GF00000004 core.py:2873 19:29:27 WARNING Stripped alignment length == 0 for GF00000004 codeml.py:225 INFO Analysing family GF00000005 core.py:2873 19:29:36 WARNING Stripped alignment length == 0 for GF00000002 codeml.py:225 INFO Analysing family GF00000006 core.py:2873 19:29:39 WARNING No codeml result for GF00000003 due to no codeml.py:234 resolved nucleotides
> > 19:55:59 WARNING No codeml result for GF00006547 due to no codeml.py:234 resolved nucleotides 19:56:16 INFO Saving to wgd_ksd/Aquilegia_coerulea.tsv.ks.tsv cli.py:493 19:56:18 INFO Making plots cli.py:495 INFO No valid Ks values for plotting cli.py:497
> 
> Conda wouldn't install `paml v4.9j` automately, some other versions instead. Could you double check the `paml` version in your conda environment for `wgd`?


I export the path of paml v4.9j. 

export PATH=$PATH:/home/software/GENOMETOOLS/PAML/paml4.9j/bin

It worked with the earlier version.
GF00000001 for conda.
[GF00000001_ks.txt.csv](https://github.com/heche-psb/wgd/files/12598744/GF00000001_ks.txt.csv)
[pro.aln.txt](https://github.com/heche-psb/wgd/files/12598745/pro.aln.txt)
[pro.fasta.txt](https://github.com/heche-psb/wgd/files/12598746/pro.fasta.txt)

**Comment by heche-psb** [comment]
I opened a new virtual environment and reinstalled `v2.0.23` and `wgd ksd` runs fine. I can't reproduce your error. Not sure if other users had the same problem only with `v2.0.23`.

**Comment by Bio1nform** [comment]
Hi, Both the PYPI and the conda version works fine.

When i run: **wgd syn -f mRNA -a Name wgd_dmd/Aquilegia_coerulea.tsv Aquilegia_coerulea.gff3 -ks wgd_ksd/Aquilegia_coerulea.tsv.ks.tsv -o wgd_sync**

The output figure seems bit different.

![Aquilegia_coerulea-vs-Aquilegia_coerulea_Ks dot_unit_gene](https://github.com/heche-psb/wgd/assets/24925652/9c6bd221-f088-4d6c-8c1e-3b0f89bca7c2)
![Aquilegia_coerulea-vs-Aquilegia_coerulea dot](https://github.com/heche-psb/wgd/assets/24925652/b9ac428f-741d-4b93-a1b7-f8bd0049340a)
![Aquilegia_coerulea-vs-Aquilegia_coerulea dot_unit_gene](https://github.com/heche-psb/wgd/assets/24925652/f0ab3427-6b4c-49b0-9a05-388956f6323a)
![Aquilegia_coerulea-vs-Aquilegia_coerulea_Ks dot](https://github.com/heche-psb/wgd/assets/24925652/6ad3b0be-86b1-4eb3-babb-2072ceb88f60)

**Comment by heche-psb** [comment]
Two types of dotplot were inferred, one is in the unit of gene (Number of genes), and one is in the unit of base (Number of bases).  The file name should contain this piece of information.

**Comment by Bio1nform** [comment]
> Two types of dotplot were inferred, one is in the unit of gene (Number of genes), and one is in the unit of base (Number of bases). The file name should contain this piece of information.

I am not getting this figure.
![image](https://github.com/heche-psb/wgd/assets/24925652/c079615e-f363-489d-9692-3fa8a0fa6da9)

**Comment by Bio1nform** [comment]
**wgd viz -d wgd_globalmrbh_ks/global_MRBH.tsv.ks.tsv --extraparanomeks wgd_ksd/Aquilegia_coerulea.tsv.ks.tsv -sp speciestree.nw --reweight -ap wgd_sync/iadhore-out/anchorpoints.txt -o wgd_viz_mixed_Ks_elmm --spair "Aquilegia_coerulea;Protea_cynaroides" --spair "Aquilegia_coerulea;Vitis_vinifera" --spair "Aquilegia_coerulea;Acorus_americanus" --spair "Aquilegia_coerulea;Aquilegia_coerulea" --gsmap wgd_globalmrbh_ks/gene_species.map --plotkde --plotelmm**

**From website.**
![image](https://github.com/heche-psb/wgd/assets/24925652/794a5ffa-4359-4d38-8f70-66e0ce3c64b1)

**My output** the peaks are smaller. 
![image](https://github.com/heche-psb/wgd/assets/24925652/d4d04b8a-7e92-4106-86f3-170d9124c228)

**Comment by heche-psb** [comment]
> > Two types of dotplot were inferred, one is in the unit of gene (Number of genes), and one is in the unit of base (Number of bases). The file name should contain this piece of information.
> 
> I am not getting this figure. ![image](https://user-images.githubusercontent.com/24925652/267997803-c079615e-f363-489d-9692-3fa8a0fa6da9.png)

It's simple dotplot in oxford grid. The gray dots are homologous gene pairs while red dots are anchor pairs. The transparency of dots can be manually set.

**Comment by heche-psb** [comment]
> **wgd viz -d wgd_globalmrbh_ks/global_MRBH.tsv.ks.tsv --extraparanomeks wgd_ksd/Aquilegia_coerulea.tsv.ks.tsv -sp speciestree.nw --reweight -ap wgd_sync/iadhore-out/anchorpoints.txt -o wgd_viz_mixed_Ks_elmm --spair "Aquilegia_coerulea;Protea_cynaroides" --spair "Aquilegia_coerulea;Vitis_vinifera" --spair "Aquilegia_coerulea;Acorus_americanus" --spair "Aquilegia_coerulea;Aquilegia_coerulea" --gsmap wgd_globalmrbh_ks/gene_species.map --plotkde --plotelmm**
> 
> **From website.** ![image](https://user-images.githubusercontent.com/24925652/267998114-794a5ffa-4359-4d38-8f70-66e0ce3c64b1.png)
> 
> **My output** the peaks are smaller. ![image](https://user-images.githubusercontent.com/24925652/267999333-d4d04b8a-7e92-4106-86f3-170d9124c228.png)

Both node-averaged and node-weighted plots will be produced. Could you show both?

**Comment by Bio1nform** [comment]
> > **wgd viz -d wgd_globalmrbh_ks/global_MRBH.tsv.ks.tsv --extraparanomeks wgd_ksd/Aquilegia_coerulea.tsv.ks.tsv -sp speciestree.nw --reweight -ap wgd_sync/iadhore-out/anchorpoints.txt -o wgd_viz_mixed_Ks_elmm --spair "Aquilegia_coerulea;Protea_cynaroides" --spair "Aquilegia_coerulea;Vitis_vinifera" --spair "Aquilegia_coerulea;Acorus_americanus" --spair "Aquilegia_coerulea;Aquilegia_coerulea" --gsmap wgd_globalmrbh_ks/gene_species.map --plotkde --plotelmm**
> > **From website.** ![image](https://user-images.githubusercontent.com/24925652/267998114-794a5ffa-4359-4d38-8f70-66e0ce3c64b1.png)
> > **My output** the peaks are smaller. ![image](https://user-images.githubusercontent.com/24925652/267999333-d4d04b8a-7e92-4106-86f3-170d9124c228.png)
> 
> Both node-averaged and node-weighted plots will be produced. Could you show both?

Aquilegia_coerulea_Corrected.ksd.weighted.svg

![image](https://user-images.githubusercontent.com/24925652/267999333-d4d04b8a-7e92-4106-86f3-170d9124c228.png)

![image](https://github.com/heche-psb/wgd/assets/24925652/1a868560-c6da-465d-ad56-a81db50d74d0)

![image](https://github.com/heche-psb/wgd/assets/24925652/92dfcb6b-a8f8-41cf-a37e-2f67b9797839)

**Comment by heche-psb** [comment]
I think it might be linked with the data we used. What is your source of the `Aquilegia coerulea` cds file in use?

**Comment by Bio1nform** [comment]
I used CDS from phytozome (https://phytozome-next.jgi.doe.gov/info/Acoerulea_v3_1)

The NCBI version of Aquilegia coerulea CDS has several genes with duplicate names. wgd cannot handle duplicated names.

>Aqcoe0131s0003.1
ATGTATATTAAATATGTCACAACCAAAAAAAACTATTGTACTGTTACATATATGCAGGGGGGTACATACAGTATACAAGG
ACGAATCCAGGGGGTGCACGGTGCAACCGCACCCCCAAAATTTGAAATTTTCATTATTTTCCCTATGTTTTTTTGTACAT
ATATCATTATTTCCCTATGCTTTTTGCACGTATATAAAAAATTTAGCTTAAATATGTAG
>Aqcoe0131s0002.1
ATGGTAGATATTACAATTTCTAGGGCACGTTGGACGGAATCAAGATCAAAACTCAAAAAAGATACTATACGACCTTTAAT
TACTCTTTCAGAGCCAAATCCGTACTACATGGTGTCTTTACGCATTGGTACA
>Aqcoe1729s0001.1

**Comment by heche-psb** [comment]
Are you using this file `Acoerulea_322_v3.1.cds_primaryTranscriptOnly.fa.gz` ?

**Comment by Bio1nform** [comment]
**wgd syn -f mRNA -a Name wgd_dmd/Aquilegia_coerulea.tsv Aquilegia_coerulea.gff3 -ks gd_ksd/Aquilegia_coerulea.tsv.ks.tsv -o wgd_sync**

I used Acoerulea_322_v3.1.cds.fa.gz (43550). 
To match to mRNA in .gff3 file (43550).

**Comment by heche-psb** [comment]
By principle, only one sequence per gene should be used in the construction of whole paranome, that way each split in the tree can represent one gene duplication event. If you use the whole alternative CDS instead of only the primary ones, how do you interpret the biological meaning of each bipartition in the tree?

**Comment by Bio1nform** [comment]
The issue is the gene names from the **Acoerulea_322_v3.1.cds_primaryTranscriptOnly.fa.gz** does not match the gff3 files.

Here is the gff3 file:
##gff-version 3
##annot-version v3.1
##species Aquilegia coerulea
Chr_01	phytozomev11	gene	2657	4987	.	+	.	ID=Aqcoe1G000100.v3.1;Name=Aqcoe1G000100;ancestorIdentifier=Aquca_009_00001.v1.1
Chr_01	phytozomev11	mRNA	2657	4987	.	+	.	ID=Aqcoe1G000100.1.v3.1;Name=Aqcoe1G000100.1;pacid=33083967;longest=1;ancestorIdentifier=Aquca_009_00001.1.v1.1;Parent=Aqcoe1G000100.v3.1
Chr_01	phytozomev11	five_prime_UTR	2657	2841	.	+	.	ID=Aqcoe1G000100.1.v3.1.five_prime_UTR.1;Parent=Aqcoe1G000100.1.v3.1;pacid=33083967
Chr_01	phytozomev11	five_prime_UTR	4435	4439	.	+	.	ID=Aqcoe1G000100.1.v3.1.five_prime_UTR.2;Parent=Aqcoe1G000100.1.v3.1;pacid=33083967
Chr_01	phytozomev11	CDS	4440	4691	.	+	0	ID=Aqcoe1G000100.1.v3.1.CDS.1;Parent=Aqcoe1G000100.1.v3.1;pacid=33083967
Chr_01	phytozomev11	three_prime_UTR	4692	4987	.	+	.	ID=Aqcoe1G000100.1.v3.1.three_prime_UTR.1;Parent=Aqcoe1G000100.1.v3.1;pacid=33083967
Chr_01	phytozomev11	gene	3331	3855	.	+	.	ID=Aqcoe1G000200.v3.1;Name=Aqcoe1G000200
Chr_01	phytozomev11	mRNA	3331	3855	.	+	.	ID=Aqcoe1G000200.1.v3.1;Name=Aqcoe1G000200.1;pacid=33082500;longest=1;Parent=Aqcoe1G000200.v3.1
Chr_01	phytozomev11	five_prime_UTR	3331	3563	.	+	.	ID=Aqcoe1G000200.1.v3.1.five_prime_UTR.1;Parent=Aqcoe1G000200.1.v3.1;pacid=33082500
Chr_01	phytozomev11	CDS	3564	3812	.	+	0	ID=Aqcoe1G000200.1.v3.1.CDS.1;Parent=Aqcoe1G000200.1.v3.1;pacid=33082500
Chr_01	phytozomev11	three_prime_UTR	3813	3855	.	+	.	ID=Aqcoe1G000200.1.v3.1.three_prime_UTR.1;Parent=Aqcoe1G000200.1.v3.1;pacid=33082500

Here are the sequence:
>Aqcoe1G000100.1
ATGAACATGGGGGACCCATCTAAACTACATGTTAAGGTCAGATTCTGCCTTGCATCAGAACTCTATTGTTGTGTCGATAC
GAGCAAAGGTGCTTTATCTGAACGGCTGGTTTCAATTAAAGAGGAAAGTATGTGCATACTCAAAGATTTTATCACCAAAC
ACAATGTTCCCACTGACATCCCTGAAGAACTTTCTGAAGCTTCTGAAGACGATGACGAAGTCTCTGAGAATCCTCCTAAG
AAACGAAAATGA
>Aqcoe1G000200.1
ATGTGTGGCATTGTGTGCGCATTAGGATTCATTCCTTCTGGGGGCACATTACCAGAACATAAATGGTTTTTCGAATTTGA
CTCCAGCTCCCACTCTTCTAGCTCAGAAACTAAATTGCTGAGTTTTCTTAAATCTTTGGAGCTCCCTGCATCCTCAATTA
GCATTCCACCCAATGGTGGTTGTTGTGTCATAAAAGGAACTTCAGGAGTTGAATGGGAAGCAAATATATTTAATTGTTCA
CTTGGTTGA

I need to remove **.1** at the end of fasta header.
And if there is any name duplication. Wgd wont work. I would have to remove the sequence with duplicated names to run.

**Comment by heche-psb** [comment]
Duplicated gene names are normally not allowed, since each gene should have a unique name. Could you use `-f mRNA` and `-a Name` for extracting the gene names?

**Comment by Bio1nform** [comment]
I used -f mRNA -a Name it works. 

The mRNA number and the gene number does not match.
genes (Acoerulea_322_v3.1.cds_primaryTranscriptOnly.fa.gz):  30023
mRNA (Acoerulea_322_v3.1.cds.fa.gz: 43550

In gff3 the genes (30023) and mRNA (43550).

**Comment by heche-psb** [comment]
OK, but now we know the difference between our results comes from the CDS data we used.

**Comment by Bio1nform** [comment]
I am getting this error.
Can you please take a look into it? I do not know what went wrong?
**wgd ksd wgd_globalmrbh**


/home/.conda/envs/wgd223_38/lib/python3.8/site-packages/Bio/Seq.py:2855: BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.
  warnings.warn(
Traceback (most recent call last):
  File "/home/.conda/envs/wgd223_38/bin/wgd", line 10, in <module>
    sys.exit(cli())
  File "/home/.conda/envs/wgd223_38/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/.conda/envs/wgd223_38/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/.conda/envs/wgd223_38/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/.conda/envs/wgd223_38/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/.conda/envs/wgd223_38/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/.conda/envs/wgd223_38/lib/python3.8/site-packages/cli.py", line 464, in ksd
    _ksd(**kwargs)
  File "/home/.conda/envs/wgd223_38/lib/python3.8/site-packages/cli.py", line 506, in _ksd
    multi_sp_plot(df,spair,spgenemap,outdir,onlyrootout,title=prefix,ylabel=ylabel,ksd=True,reweight=reweight,sptree=speciestree,extraparanomeks=extraparanomeks, ap = anchorpoints,plotkde=plotkde,plotapgmm=plotapgmm,plotelmm=plotelmm,components=components,na=True)
  File "/home/.conda/envs/wgd223_38/lib/python3.8/site-packages/wgd/viz.py", line 638, in multi_sp_plot
    kde = stats.gaussian_kde(y,weights=w,bw_method=0.1)
  File "/home/.conda/envs/wgd223_38/lib/python3.8/site-packages/scipy/stats/kde.py", line 193, in __init__
    raise ValueError("`dataset` input should have multiple elements.")
ValueError: `dataset` input should have multiple elements.

**Comment by heche-psb** [comment]
What is the complete command that you used?

**Comment by Bio1nform** [comment]
wgd ksd wgd_globalmrbh/global_MRBH.tsv --extraparanomeks wgd_ksd/Aquilegia_coerulea.tsv.ks.tsv -sp speciestree.nw --reweight -o wgd_globalmrbh_ks --spair "Aquilegia_coerulea;Protea_cynaroides" --spair "Aquilegia_coerulea;Vitis_vinifera" --spair "Aquilegia_coerulea;Acorus_americanus" --spair "Aquilegia_coerulea;Aquilegia_coerulea" --plotkde -ap wgd_syn/iadhore-out/anchorpoints.txt

**Comment by heche-psb** [comment]
It seems you forgot to give the input cds files.

**Comment by Bio1nform** [comment]
Still the same. I removed .1 from Aqcoe1G000200.1.
What do you think is the cause? ValueError: dataset input should have multiple elements.

These are the only outputs.
gene_species.map
global_MRBH.tsv.ks.tsv

wgd ksd wgd_globalmrbh_G/global_MRBH.tsv --extraparanomeks wgd_ksd_G/Aquilegia_coerulea.tsv.ks.tsv -sp speciestree.nw --reweight -o wgd_globalmrbh_ks_G --spair "Aquilegia_coerulea;Protea_cynaroides" --spair "Aquilegia_coerulea;Vitis_vinifera" --spair "Aquilegia_coerulea;Acorus_americanus" --spair "Aquilegia_coerulea;Aquilegia_coerulea" Aquilegia_coerulea Protea_cynaroides Acorus_americanus Vitis_vinifera --plotkde -ap wgd_sync_G/iadhore-out/anchorpoints.txt

**Comment by Bio1nform** [comment]
Hi I see that the speciestree somehow affects the figure output. See the arrows in the figure.


(((Acorus_americanus,Aquilegia_coerulea),Protea_cynaroides),Vitis_vinifera);
![image](https://github.com/heche-psb/wgd/assets/24925652/af91fc33-ec19-4a0b-9008-09eaf880f6d2)

The original one
(((Vitis_vinifera,Protea_cynaroides),Aquilegia_coerulea),Acorus_americanus);
![image](https://github.com/heche-psb/wgd/assets/24925652/8419979a-16c4-401d-afa4-c60dc657c404)

How did you make these speciestree file? Was it external source, if so what genes input did you use to create the file?

Thanks

**Comment by heche-psb** [comment]
The relationship of outgroup and ingroup species determines the result of substitution rate correction. When you change the species tree which alters such relationship, the result will change. I followed APG IV.

**Comment by Bio1nform** [comment]
Sorry for the naive question, how did you get the tree file? Do i download from APG IV? APG IV tree is huge tree.

![Angiosperm_Phylogeny_Poster_1500px](https://github.com/heche-psb/wgd/assets/24925652/33f7036c-ee28-4e70-ae33-21ea7506d2b3)

Thanks

**Comment by heche-psb** [comment]
I used the updated information in the [APG IV web](https://www.mobot.org/MOBOT/research/APweb/)

**Comment by Bio1nform** [comment]
wgd ksd wgd_globalmrbh/global_MRBH.tsv --extraparanomeks wgd_ksd/Hap1.tsv.ks.tsv -sp speciestree.nw --reweight -o wgd_globalmrbh_ks3 --spair "Hap1;Malus_domestica" --spair "Hap1;Araport_thalania11" --spair "Hap1;Vitis_vinifera" --spair "Hap1;Oryza_sativaJ" --spair "Hap1;Hap1" Hap1 Malus_domestica Araport_thalania11 Vitis_vinifera Oryza_sativaJ --plotkde -ap wgd_syn/iadhore-out/anchorpoints.txt


![image](https://github.com/heche-psb/wgd/assets/24925652/bff283a5-3d63-4f35-a563-6d2f61aa1db3)

I cannot see the other peaks, what could be the reason?
Thanks
