### ISSUE TITLE
erro for ksd

### ISSUE THREAD

**Issue by lfp-a** [heche-psb/wgd#8]
When I use the steps of ksd, the following error will appear, and all codeml files are empty files, how to solve it?

WARNING  No codeml result for GF00003411 due to no resolved nucleotides                                                                                                                              codeml.py:234
         INFO     Analysing family GF00003415                                                                                                                                                                  core.py:2873
         WARNING  No codeml result for GF00003412 due to no resolved nucleotides                                                                                                                              codeml.py:234
         INFO     Analysing family GF00003416                                                                                                                                                                  core.py:2873
         WARNING  No codeml result for GF00003413 due to no resolved nucleotides                                                                                                                              codeml.py:234
         INFO     Analysing family GF00003417                                                                                                                                                                  core.py:2873
         WARNING  No codeml result for GF00003414 due to no resolved nucleotides                                                                                                                              codeml.py:234
         WARNING  No codeml result for GF00003415 due to no resolved nucleotides                                                                                                                              codeml.py:234

**Comment by heche-psb** [comment]
Hi, there was a bug in `v2.0.21`. I have fixed the bug and replaced it with `v2.0.22`. Could you reinstall and try again?

**Comment by lfp-a** [comment]
Thank you very much. I'll try it right away

**Comment by lfp-a** [comment]
I have just installed a new version of 2.022. but I still have the following errors


15:12:31 WARNING  No codeml result for GF00000092 due to no resolved nucleotides                                                                                                                              codeml.py:234
         WARNING  No codeml result for GF00000093 due to no resolved nucleotides                                                                                                                              codeml.py:234
         WARNING  No codeml result for GF00000094 due to no resolved nucleotides                                                                                                                              codeml.py:234
15:12:48 WARNING  No codeml result for GF00000001 due to no resolved nucleotides                                                                                                                              codeml.py:234
15:12:48 INFO     Saving to sample.ksd/sample.fasta.tsv.ks.tsv                                                                                                                                                   cli.py:493
         INFO     Making plots                                                                                                                                                                                   cli.py:495
         INFO     No valid Ks values for plotting

**Comment by heche-psb** [comment]
Hi, this is not an error I think. It just shows that there is no Ks value can be estimated from those families because of in-frame stop codon in the alignment file that codeml couldn't handle, even though it looks like the stripped alignment length is non-zero. How many familes have you given as input in total? Did you only give those 4 large families? If you use `--cds` option at `dmd` step and `ksd` step, it might be another solution.

**Comment by lfp-a** [comment]
I don't think it's going to be this way, the comdel files in the running result are empty, I'm the cds of the entire transcriptional group data, thousands of family, and the final comdel is all empty

**Comment by heche-psb** [comment]
Could you share me with your cds file? I will try to reproduce your error.

**Comment by lfp-a** [comment]
I'll send the attachment to your mailbox

**Comment by lfp-a** [comment]
Can you provide your email address? I just replied to the email but was returned

**Comment by heche-psb** [comment]
This is my university email address Hengchi.Chen@UGent.be

**Comment by lfp-a** [comment]
It has been sent, please check it

**Comment by heche-psb** [comment]
[run_log.txt](https://github.com/heche-psb/wgd/files/12473845/run_log.txt)
As you can see, I can't reproduce your error. Are you using `paml v4.9j` and install the wgd from this github repository?

**Comment by lfp-a** [comment]
Thank you very much for your help. I have re-installed paml4.9 and now it can be used, but there are new errors like the following


This is wgd v2.0.22                                                                                                   cli.py:32
qt.qpa.xcb: could not connect to display localhost:12.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)

**Comment by heche-psb** [comment]
This error is typically encountered in Linux systems when there is a problem with the X Window System. You can try `echo $DISPLAY`. It should return something like ":0.0". If it's not set or set incorrectly, you may need to configure your X server. Or you may need to install or reinstall the Qt libraries or the xcb plugin specifically.

**Comment by lfp-a** [comment]
Thank you very much. I changed the software of the linked server to MobaXterm and it can be used

**Comment by heche-psb** [comment]
No problem. Thanks for your interest in `wgd v2` :-)

**Comment by melop** [comment]
I encountered a similar problem with ksd. Is there a way to make plots with R instead or disable plotting? It is difficult to setup X environment on computing nodes without a GUI.
